version: '3.4'

services:
  searchapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"

  searchhandler1:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  searchhandler2:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  searchhandler3:
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  searchtargetapi1:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  notificationapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8082:80"

  logapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8083:80"

